var profiles = [{
"login": "datLucius",
"id": 12485499,
"avatar_url": "https://avatars.githubusercontent.com/u/12485499?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/datLucius",
"html_url": "https://github.com/datLucius",
"followers_url": "https://api.github.com/users/datLucius/followers",
"following_url": "https://api.github.com/users/datLucius/following{/other_user}",
"gists_url": "https://api.github.com/users/datLucius/gists{/gist_id}",
"starred_url": "https://api.github.com/users/datLucius/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/datLucius/subscriptions",
"organizations_url": "https://api.github.com/users/datLucius/orgs",
"repos_url": "https://api.github.com/users/datLucius/repos",
"events_url": "https://api.github.com/users/datLucius/events{/privacy}",
"received_events_url": "https://api.github.com/users/datLucius/received_events",
"type": "User",
"site_admin": false,
"name": "Lucius Nelson",
"company": "",
"blog": "",
"location": "Charleston, SC",
"email": "",
"hireable": false,
"bio": null,
"public_repos": 11,
"public_gists": 0,
"followers": 1,
"following": 3,
"created_at": "2015-05-17T17:14:36Z",
"updated_at": "2015-05-19T17:44:37Z"
}]
